Angular 13 & rxjs 7
maplibre/ngx-maplibre-gl pull request #28
Opened 2022-01-17 16:58 UTC by hheexx

Interested?
Watch out for changed package name and versions.

2022-01-17 21:40 UTC, HarelM commented
Thanks!!!
I want to finilize maplibre 12 with all the typescript changes first and then create a version with a "good" maplibre version, and then I'll merge this.
Can you change the version of this package to 13.0.0 so that when I merge all I will have to do is click the publish button?

2022-01-17 22:01 UTC, hheexx commented
Contact me when you plan to merge, I will fix it.
One more thing to consider is rxjs. I updated here to rxjs 7 but i'm not sure what that implies....

2022-01-17 22:03 UTC, HarelM commented
Did you use some tool to upgrade? I might want to update my project to angular 13 to test this as well...

2022-01-17 22:10 UTC, hheexx commented
npx ng update everything. It has schematics that made some thanges.
Then I updated remaining libs manualy in package.json

2022-01-17 23:19 UTC, hheexx commented
angular material and angular forms removed as it's not used....

2022-01-19 22:12 UTC, HarelM commented
Seems like the tests are failing.
I think the showcase is using material so it shouldn't be removed...?

2022-01-19 22:13 UTC, HarelM commented
Would you be integrated in helping me maintain this library?
I moved to angular 13 too in my project, so this is going to happen soon I guess :-)

2022-01-19 23:44 UTC, hheexx commented
Ok, I will bring it back.
I could help with a lib....

2022-01-20 05:48 UTC, HarelM commented on projects/ngx-maplibre-gl/package.json
> +  "name": "@codezen/ngx-maplibre-gl",
Nope...

2022-01-20 05:48 UTC, HarelM commented on projects/ngx-maplibre-gl/src/lib/source/geojson/feature.component.ts
> +    this.GeoJSONSourceComponent.updateFeatureData.next(null);
Better to send undefined?

2022-01-20 05:50 UTC, HarelM requested changes
Also I guess you are using node 16, I think it will be better to do it in another commit...

2022-01-21 19:58 UTC, hheexx commented
> Also I guess you are using node 16, I think it will be better to do it in another commit...

How you see that?

2022-01-21 20:02 UTC, HarelM commented
The changes in the lock file

2022-01-21 20:03 UTC, HarelM commented
I've activated the tests again as they were not ruining for some reason. Make sure to fix the failing tests as well.

2022-01-21 20:28 UTC, hheexx commented
> The changes in the lock file

Aha. It;s not node related but npm related. npm versions >6 create it but all recent  versions of npm@6 also read it.
try npm i npm -g

2022-01-21 21:09 UTC, HarelM commented
The errors message is a bit strange. Can you check if these tests pass locally?

2022-01-21 22:25 UTC, hheexx commented
> The errors message is a bit strange. Can you check if these tests pass locally?
yea strange. I dont have chrome, i tried e2e tests with firefox and everything look ok.

2022-01-22 13:24 UTC, HarelM commented
Can you try and rebase? I think I managed to fix the failing tests.

2022-01-22 21:33 UTC, HarelM commented
I've created a branch for node 16. I'll merge it soon. I still don't know what's wrong with the language switch test as it passes locally on my machine. but I'm using mac and not ubuntu. I'll need to dig into it, but that shouldn't hold this PR.
I'll work on it in the next few days.
Thanks for tolerating my annoying comments :-)
Let me know if you would like to help maintain this repo as currently I'm the only maintainer which is not ideal...

2022-01-22 21:44 UTC, hheexx commented
Thanks!
Yea I'm OK with dedicating some time for this....
ill keep it updated at least.

2022-01-23 11:28 UTC, HarelM commented
I've added you with write permissions.

2022-01-24 17:21 UTC, hheexx commented
so I merge?

2022-01-24 17:52 UTC, HarelM commented
Can you rebase? I've updated to node 16 in another branch.

2022-01-24 17:53 UTC, HarelM approved these changes

2022-01-24 18:22 UTC, HarelM approved these changes

2022-01-24 18:23 UTC, HarelM commented
Thanks!! Any chance you can see if you can solve the the failing tests?
Not related to this PR of course...

2022-01-24 18:23 UTC, merged